[package]
name = "yew-app"
version = "0.1.0"
edition = "2024"

[dependencies]
log = "0.4.28"
wasm-logger = "0.2.0"
web-sys = { version = "0.3.82", features = ["KeyboardEvent"]}
# this is the development version of Yew
yew = { git = "https://github.com/yewstack/yew/", features = ["csr"] }
